import type { IncomingHttpHeaders } from "http";
import type { Config } from "@/node/config";
import type { AIService } from "@/node/services/aiService";
import type { ProjectService } from "@/node/services/projectService";
import type { WorkspaceService } from "@/node/services/workspaceService";
import type { MuxGatewayOauthService } from "@/node/services/muxGatewayOauthService";
import type { MuxGovernorOauthService } from "@/node/services/muxGovernorOauthService";
import type { CodexOauthService } from "@/node/services/codexOauthService";
import type { CopilotOauthService } from "@/node/services/copilotOauthService";
import type { OnePasswordService } from "@/node/services/onePasswordService";
import type { ProviderService } from "@/node/services/providerService";
import type { TerminalService } from "@/node/services/terminalService";
import type { EditorService } from "@/node/services/editorService";
import type { WindowService } from "@/node/services/windowService";
import type { UpdateService } from "@/node/services/updateService";
import type { TokenizerService } from "@/node/services/tokenizerService";
import type { ServerService } from "@/node/services/serverService";
import type { MenuEventService } from "@/node/services/menuEventService";
import type { VoiceService } from "@/node/services/voiceService";
import type { MCPConfigService } from "@/node/services/mcpConfigService";
import type { McpOauthService } from "@/node/services/mcpOauthService";
import type { ExperimentsService } from "@/node/services/experimentsService";
import type { WorkspaceMcpOverridesService } from "@/node/services/workspaceMcpOverridesService";
import type { MCPServerManager } from "@/node/services/mcpServerManager";
import type { TelemetryService } from "@/node/services/telemetryService";
import type { SigningService } from "@/node/services/signingService";
import type { SessionTimingService } from "@/node/services/sessionTimingService";
import type { SessionUsageService } from "@/node/services/sessionUsageService";
import type { TaskService } from "@/node/services/taskService";
import type { DevToolsService } from "@/node/services/devToolsService";
import type { PolicyService } from "@/node/services/policyService";
import type { CoderService } from "@/node/services/coderService";
import type { ServerAuthService } from "@/node/services/serverAuthService";
import type { SshPromptService } from "@/node/services/sshPromptService";
import type { AnalyticsService } from "@/node/services/analytics/analyticsService";
import type { DesktopBridgeServer } from "@/node/services/desktop/DesktopBridgeServer";
import type { DesktopSessionManager } from "@/node/services/desktop/DesktopSessionManager";
import type { DesktopTokenManager } from "@/node/services/desktop/DesktopTokenManager";

export interface ORPCContext {
  config: Config;
  aiService: AIService;
  projectService: ProjectService;
  workspaceService: WorkspaceService;
  taskService: TaskService;
  providerService: ProviderService;
  muxGatewayOauthService: MuxGatewayOauthService;
  muxGovernorOauthService: MuxGovernorOauthService;
  codexOauthService: CodexOauthService;
  copilotOauthService: CopilotOauthService;
  onePasswordService?: OnePasswordService | null;
  terminalService: TerminalService;
  editorService: EditorService;
  windowService: WindowService;
  updateService: UpdateService;
  tokenizerService: TokenizerService;
  serverService: ServerService;
  menuEventService: MenuEventService;
  voiceService: VoiceService;
  mcpConfigService: MCPConfigService;
  mcpOauthService: McpOauthService;
  workspaceMcpOverridesService: WorkspaceMcpOverridesService;
  mcpServerManager: MCPServerManager;
  sessionTimingService: SessionTimingService;
  telemetryService: TelemetryService;
  experimentsService: ExperimentsService;
  sessionUsageService: SessionUsageService;
  devToolsService: DevToolsService;
  policyService: PolicyService;
  signingService: SigningService;
  coderService: CoderService;
  serverAuthService: ServerAuthService;
  sshPromptService: SshPromptService;
  analyticsService: AnalyticsService;
  desktopSessionManager: DesktopSessionManager;
  desktopTokenManager: DesktopTokenManager;
  desktopBridgeServer: DesktopBridgeServer;
  headers?: IncomingHttpHeaders;
}
